import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
// };
export const metadata = {
  title: "POB Trust",
  description: "Generated by create next app",
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    images: [
      {
        url: "https://pob.datainovate.com/backend//storage/app/home_page_slider/924163_1752845154.webp",
        width: 1200,
        height: 630,
        alt: "POB",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
